import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.functions._

object KafkaStructuredWordCount {
  def main(args: Array[String]): Unit = {

    // 1. Initialize the Spark Session
    val spark = SparkSession.builder()
      .appName("KafkaStructuredWordCount")
      .master("local[*]") // Run locally using all available cores
      .getOrCreate()

    // Import implicits for encoding Datasets (e.g., as[String])
    import spark.implicits._

    // 2. Read the stream from Kafka
    // Kafka source schemas contain: key, value, topic, partition, offset, timestamp, timestampType
    val kafkaStreamDf = spark.readStream
      .format("kafka")
      .option("kafka.bootstrap.servers", "localhost:9092") // Replace with your broker address
      .option("subscribe", "customersupport")             // Your source Kafka topic
      .option("startingOffsets", "latest")                 // Read only new data
      .load()

    // 3. Process and transform the data
    // Convert the binary 'value' column from Kafka into a readable String
    val linesDs = kafkaStreamDf
      .selectExpr("CAST(value AS STRING)")
      .as[String]

    // Split sentences into individual words and filter out empty strings
    val wordsDs = linesDs
      .flatMap(line => line.split("\\s+"))
      .filter(_ != "")

    // 4. Generate the running count by grouping by word column
    val wordCountsDf = wordsDs
      .groupBy("value") // The column generated by default from a Dataset[String] is named "value"
      .count()
      .withColumnRenamed("value", "word")

    // 5. Start streaming query and output to the console
    val query = wordCountsDf.writeStream
      .outputMode("complete")         // "complete" is required for streaming aggregations without watermarks
      .format("console")              // Prints the output table directly to the console
      .option("checkpointLocation", "/tmp/spark-kafka-checkpoint") // Essential for fault tolerance
      .start()

    // Keep the application running until manually terminated
    query.awaitTermination()
  }
}
